type: adan


lr: 1.0
weight_decay: 1e-4
eps: 1e-6
amsgrad: false
beta2: 0.95


# scheduler, choose from [cosine, inverse_sqrt, cosine_with_restarts, cosine_with_min_lr, warmup_stable_decay] 
# they say to use the same learning rate scheduler you would normally use in the problem so i am sticking with cosine 
scheduler_type: cosine


warmup: 0.1
max_iters: ???
